- name: Test FTP speed
  hosts: '{{hosts}}'
  vars:
    ftp_server: '{{server}}'
    get_ftp_username: '{{getusername}}'
    get_ftp_password: '{{getpassword}}'
    ftp_file: '{{filepath}}'
    put_ftp_username: '{{putusername}}'
    put_ftp_password: '{{putpassword}}'
  tasks:
    - name: Upload a file to FTP server
      shell: |
        ftp -n {{ ftp_server }} << EOF
        user {{ put_ftp_username }} {{ put_ftp_password }}
        binary
        put {{ ftp_file }}
        bye
        EOF
      register: ftp_upload_result
    - name: Download a file from FTP server
      shell: |
        ftp -n {{ ftp_server }} << EOF
        user {{ get_ftp_username }} {{ get_ftp_password }}
        binary
        get {{ ftp_file }} {{ ftp_file }}
        bye
        EOF
      register: ftp_download_result
    - name: Print FTP speed test results
      debug:
        var: item.stdout_lines
      with_items:
        - "{{ ftp_download_result }}"
        - "{{ ftp_upload_result }}"
